New workflows that work locally as well (#3)
* update

* update

* update

* update

* update

* update

* update

* update

* update

* update

* update

* update

* update

* update

* update

* update

* update

* update

* update

diff --git a/download_binary/action.yml b/download_binary/action.yml
--- a/download_binary/action.yml
+++ b/download_binary/action.yml
@@ -24,32 +24,45 @@ runs:
     - shell: bash
       run: |
 
-        if [ "${{ inputs.tag }}" = "latest" ]; then
-          ABC=$(curl --silent \
-          -H "Accept: application/vnd.github.v3+json" \
-          -H "Authorization: token ${{ inputs.token }}" \
-          https://api.github.com/repos/${{ github.repository }}/releases/latest | jq .)
+        RUN_ID=${{ github.run_id }}
+
+        if [[ $RUN_ID -eq 1 ]]; then
+          echo "Running in a development environment locally with https://github.com/nektos/act"
+
+          curl --silent \
+          host.docker.internal:8000/${{ inputs.name }} \
+          -L \
+          --output ${{ inputs.name }}
+
         else
-          ABC=$(curl --silent \
-          -H "Accept: application/vnd.github.v3+json" \
+
+          if [ "${{ inputs.tag }}" = "latest" ]; then
+            ABC=$(curl --silent \
+            -H "Accept: application/vnd.github.v3+json" \
+            -H "Authorization: token ${{ inputs.token }}" \
+            https://api.github.com/repos/${{ github.repository }}/releases/latest | jq .)
+          else
+            ABC=$(curl --silent \
+            -H "Accept: application/vnd.github.v3+json" \
+            -H "Authorization: token ${{ inputs.token }}" \
+            https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ inputs.tag }} | jq .)
+          fi
+
+          if [ "$(echo $ABC | jq -r .message)" = "Not Found" ]; then
+            echo "Couldn't find tag"
+            exit 1
+          fi
+
+          ASSET_ID=$(echo $ABC | jq ".assets[] | {id, name}" | jq '. | select( .name == "'${{ inputs.name }}'")' | jq -r .id)
+
+          curl --silent \
+          -H "Accept: application/octet-stream" \
           -H "Authorization: token ${{ inputs.token }}" \
-          https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ inputs.tag }} | jq .)
+          https://api.github.com/repos/${{ github.repository }}/releases/assets/$ASSET_ID \
+          -L \
+          --output ${{ inputs.name }}
+
         fi
-
-        if [ "$(echo $ABC | jq -r .message)" = "Not Found" ]; then
-          echo "Couldn't find tag"
-          exit 1
-        fi
-
-        ASSET_ID=$(echo $ABC | jq ".assets[] | {id, name}" | jq '. | select( .name == "'${{ inputs.name }}'")' | jq -r .id)
-
-        curl --silent \
-        -H "Accept: application/octet-stream" \
-        -H "Authorization: token ${{ inputs.token }}" \
-        https://api.github.com/repos/${{ github.repository }}/releases/assets/$ASSET_ID \
-        -L \
-        --output ${{ inputs.name }}
 
         chmod +x ${{ inputs.name }}
-
         echo "::set-output name=binary::${{ inputs.name }}"
diff --git a/window/action.yml b/window/action.yml
--- a/window/action.yml
+++ b/window/action.yml
@@ -20,6 +20,24 @@ runs:
         RUN_ID=${{ github.run_id }}
         RUN_NUMBER=${{ github.run_number }}
 
+        if [[ $RUN_ID -eq 1 ]]; then
+          echo "Running in a development environment locally with https://github.com/nektos/act"
+
+          if [ -z "${{ github.event.inputs.start_time }}" ]; then
+            echo "github.event.inputs.start_time is missing"
+            exit 1
+          fi
+
+          if [ -z "${{ github.event.inputs.end_time }}" ]; then
+            echo "github.event.inputs.end_time is missing"
+            exit 1
+          fi
+
+          echo "::set-output name=start_time::${{ github.event.inputs.start_time }}"
+          echo "::set-output name=end_time::${{ github.event.inputs.end_time }}"
+          exit 0
+        fi
+
         ABC=$(curl --silent \
         -H "Accept: application/vnd.github.v3+json" \
         -H "Authorization: token ${{ inputs.token }}" \
@@ -34,10 +52,19 @@ runs:
         "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$WORKFLOW_ID/runs?status=success&per_page=1&created=<$END_TIME&branch=${{ github.ref_name }}" | jq .)
 
         if [[ $(echo $DEF | jq -r .total_count) -eq 0 ]]; then
-        START_TIME=$END_TIME
+          START_TIME=$END_TIME
         else
-        START_TIME=$(echo $DEF | jq -r .workflow_runs[].created_at)
+          START_TIME=$(echo $DEF | jq -r .workflow_runs[].created_at)
         fi
 
-        echo "::set-output name=start_time::$START_TIME"
-        echo "::set-output name=end_time::$END_TIME"
+        if [ -z "${{ github.event.inputs.start_time }}" ]; then
+          echo "::set-output name=start_time::$START_TIME"
+        else
+          echo "::set-output name=start_time::${{ github.event.inputs.start_time }}"
+        fi
+
+        if [ -z "${{ github.event.inputs.end_time }}" ]; then
+          echo "::set-output name=end_time::$END_TIME"
+        else
+          echo "::set-output name=end_time::${{ github.event.inputs.end_time }}"
+        fi
